#lang scheme
(define LOCATIONS '( 
(venice 150 (milan bologna florence) (concert opera festival))
(milan 130 (venice bologna florence turin bern) (fashion concert))
(florence 130 (milan bologna venice) (concert opera festival))
(bologna 100 (milan florence) (concert festival))
(bern 150 (milan zurich) (concert festival theatre science))
(zurich 170 (bern munich) (concert theatre))
(munich 170 (zurich stuttgart frankfurt salzburg vienna) (concert festival))
(stuttgart 130 (munich frankfurt) (concert opera))
(frankfurt 130 (stuttgart frankfurt) (concert theatre))
(salzburg 130 (munich vienna) (concert opera theatre))
(vienna 170 (munich salzburg) (concert opera theatre))
(nice 150 (cannes monaco) (opera theatre))
(cannes 170 (nice monaco) (festival theatre))
(monaco 170 (nice cannes) (casino concert))
(barcelona 130 (zaragoza mallorca ibiza) (casino concert theatre football))
(zaragoza 90 (barcelona madrid) (football))
(madrid 100 (zaragoza valencia) (theatre concert))
(valencia 90 (madrid mallorca) (casino concert))
(mallorca 170 (valencia barcelona ibiza) (festival concert))
(ibiza 170 (mallorca barcelona) (concert festival))
)) 

(define TRAVELERS '( 
(hans (madrid valencia) (theatre concert opera) frankfurt)
(sergio (barcelona milan bologna) (theatre opera) florence)
(john (milan barcelona valencia cannes zaragoza) (football concert fashion) monaco)
(sisi (madrid munich bern) (concert opera science) vienna)
(salma (venice bologna barcelona madrid) (theatre festival) mallorca)
(messi (ibiza florence nice vienna milan venice) (concert festival) barcelona)
(ronaldo (mallorca ibiza cannes nice) (concert opera) madrid)
(medici (madrid zurich) (opera) florence)
(james (barcelona florence bologna) (concert opera football) venice)
(kate (nice bern ibiza zaragoza) (football festival science) milan)
(hagrid (mallorca zaragoza ibiza milan) (football fashion theatre) bologna)
(harry (valencia cannes florence) (football concert fashion) bern)
(dumbledore (milan bern) (science fashion) zurich)
(hermione (salzburg barcelona florence cannes) (football theatre festival) munich)
(ron (milan cannes salzburg) (theatre fashion) stuttgart)
(dolores (milan cannes vienna) (festival concert) salzburg)
(maeve (bern monaco ibiza vienna) (opera concert science) nice)
(cercei (vienna barcelona valencia mallorca bologna) (football opera) cannes)
(arya (mallorca ibiza frankfurt munich bologna madrid) (opera concert) zaragoza)
(sansa (milan barcelona valencia cannes zaragoza) (football concert fashion) valencia)
)) 
